name: Benchmarks-pr

on:
  pull_request:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  benchmark-pr-to-main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: pr

      - uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - run: |
          echo "Running benchmarks"
          pushd pr/benchmarks/Benchmarks
          dotnet run --configuration Release -- --filter '*' --exporters json --job Short
          mv BenchmarkDotNet.Artifacts/results/Benchmarks.Benchmarks-report-full-compressed.json $RUNNER_TEMP/benchmarks-pr.json
          popd
        name: Run benchmarks for PR

      - run: tree -a

      - run: |
          echo Temp $RUNNER_TEMP
          pushd $RUNNER_TEMP
          tree -a
          popd
