name: Benchmarks-pr

on:
  pull_request:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  benchmark-pr-to-main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: pr

      - uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - run: |
          echo "Running benchmarks"
          pushd pr/benchmarks/Benchmarks

          # Run benchmarks for PR
          dotnet run --configuration Release -- --filter '*' --exporters json --job Short
          mv BenchmarkDotNet.Artifacts/results/Benchmarks.Benchmarks-report-full-compressed.json $RUNNER_TEMP/benchmarks-pr.json

          # Run benchmarks for main
          export SimplifiedSearchCsprojPath=../../../main/src/SimplifiedSearch/SimplifiedSearch.csproj
          dotnet run --configuration Release -- --filter '*' --exporters json --job Short
          mv BenchmarkDotNet.Artifacts/results/Benchmarks.Benchmarks-report-full-compressed.json $RUNNER_TEMP/benchmarks-main.json

          popd
        name: Run benchmarks for PR

      - run: tree -a

      - run: |
          echo Temp $RUNNER_TEMP
          pushd $RUNNER_TEMP
          tree -a
          popd

      - run: |
          echo MAIN
          cat $RUNNER_TEMP/benchmarks-main.json

          echo PR
          cat $RUNNER_TEMP/benchmarks-pr.json
        name: cat results

      - name: Store baseline
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: MainVsPrBenchmark
          tool: 'benchmarkdotnet'
          output-file-path: $RUNNER_TEMP/benchmarks-main.json
          auto-push: false
          external-data-json-path: $RUNNER_TEMP/benchmarks-comparison.json

      - name: Compare pr
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: MainVsPrBenchmark
          tool: 'benchmarkdotnet'
          output-file-path: $RUNNER_TEMP/benchmarks-pr.json
          auto-push: false
          external-data-json-path: $RUNNER_TEMP/benchmarks-comparison.json
          alert-threshold: '120%'
          fail-on-alert: true
