name: Benchmarks-pr

on:
  pull_request:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  benchmark-pr-to-main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: pr

      - uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - run: |
          echo "Running benchmarks"
          pushd pr/benchmarks/Benchmarks

          # Run benchmarks for PR
          dotnet run --configuration Release -- --filter '*' --exporters json --job Short
          mv BenchmarkDotNet.Artifacts/results/Benchmarks.Benchmarks-report-full-compressed.json ../../../benchmarks-pr.json

          # Run benchmarks for main
          export SimplifiedSearchCsprojPath=../../../main/src/SimplifiedSearch/SimplifiedSearch.csproj
          dotnet run --configuration Release -- --filter '*' --exporters json --job Short
          mv BenchmarkDotNet.Artifacts/results/Benchmarks.Benchmarks-report-full-compressed.json ../../../benchmarks-main.json

          popd
        name: Run benchmarks for PR

      - run: tree -a
      
      - run: ls -l

      - name: Store baseline
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: MainVsPrBenchmark
          tool: 'benchmarkdotnet'
          output-file-path: benchmarks-main.json
          auto-push: false
          external-data-json-path: benchmarks-comparison.json

      - name: Compare pr
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: MainVsPrBenchmark
          tool: 'benchmarkdotnet'
          output-file-path: benchmarks-pr.json
          auto-push: false
          external-data-json-path: benchmarks-comparison.json
          alert-threshold: '120%'
          fail-on-alert: true
