name: SimplifiedSearch-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]
        buildConfiguration: [ 'Debug', 'Release' ]

    steps:
    - uses: actions/checkout@v7
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c ${{ matrix.buildConfiguration }} --no-restore
    - name: Test
      run: dotnet test -c ${{ matrix.buildConfiguration }} --no-build

  mutation-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Tools
      run: dotnet tool restore

    - name: Stryker main
      if: github.ref == 'refs/heads/main'
      run: dotnet stryker --version "${{ github.ref_name }}" --reporter Dashboard
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

    - name: Stryker branch
      if: github.ref != 'refs/heads/main'
      run: dotnet stryker --since:main --version "${{ github.ref_name }}" --reporter Dashboard
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
